### ISSUE TITLE
Allow >512 octets

### ISSUE THREAD

**Issue by martinthomson** [dohwg/draft-ietf-doh-dns-over-https#110]
Whether or not RFC 1035 has this limit, DOH should not.

**Comment by raybellis** [comment]
The relevant text in RFC 1035 is:

> Messages carried by UDP are restricted to 512 bytes (not counting the IP
or UDP headers).  Longer messages are truncated and the TC bit is set in
the header.

If the DOH protocol is referred to as `dns-udpwireformat` "per RFC 1035" then readers of the spec would IMHO be inclined to believe that the 512 byte limit applies.

**Comment by fantuz** [comment]
Hello @raybellis !
as quite a bunch of records are indeed > 512.... some companies set 1024~4096 as operational limit on forwarders and routers. Maybe it could be set in draft to 1024, to avoid jumboframes at all in the picture ?

Maybe RFC1035 not have foreseen the increasing size of messaging we then experienced lately (along with Add and Auth getting bigger for redundancy) ? no doubts on it, people are creative about what they can put inside DNS: geo-informations in LOC type, or surf web within TXT records, PGP keys ...

I can personally get along most of times with 50-100 bytes average packet size in a simple browsing session, but carrying DNSSEC or even just an SPF will make the use of TCP on DNS backend more and more and more exclusive... I am not saying is any bad/good.

We risk limiting the "native DNS" initial use of UDP (which has probably grown after 1035 initial needs) by reverting back to quite an "old" setting. I am not sure everyone today does truncate on exact 512, I might be very wrong. Little higher limit can still be beneficial to transport, compression, stateless/stateful costs etc.

By the way, one of today's standing argument by Sir P. Mockapretis, is indeed the present limit on the size of datagrams, just to make things funnier !

Making a parallel with the transport layer, we do not want to drive trough TCP-only world as we had also mentioned QUIC and others. Another parallel on semantics, we almost mention HTTP3 just because comes after HTTP2 but nothing lower than 2.  So why shall we not leave that choice OPEN to implementors, to set the desired truncating threshold starting at 512 an up ? Are there references to present RFC on the topic to help reasoning or delegate the choice on this ?

The truncate decision for an ANSWER having size > threshold is taken only by server, client will accept and parse so no impact ? Can we try to elaborate on this ?

Just brainstorming...

**Comment by vttale** [comment]
> Maybe it could be set in draft to 1024, to avoid jumboframes at all in the picture ?

Goodness no, not the least of which being because https transport issues are clearly out of scope for this work.

**Comment by emanjon** [comment]
>The truncate decision for an ANSWER having size > threshold is taken only by server, client will accept and parse so no impact ? Can we try to elaborate on this ?

The server may have gotten a truncated response from an an authoritative name server, so the client always need to expect an truncated response (except in some local uses of DNS). YES, Seems like something that should be elaborated on.

**Comment by paulehoffman** [comment]
Proposed fix at #120

**Comment by mcmanus** [comment]
closed by #120 .. we can reopen this issue if necessary

**Comment by mcmanus** [comment]
reopen to consider #123
