### ISSUE TITLE
Clear up point about MTI server response format

### ISSUE THREAD

**Issue by martinthomson** [dohwg/draft-ietf-doh-dns-over-https#111]
The fact that an HTTP server can provide a response in the format of its choice was not well understood by DNS people.  This motivates the MTI format for servers.

**Comment by paulehoffman** [comment]
On 2018-03-25, @bemasc sent the following to the list:

At the meeting in London last week, we asked the room for opinions on two topics:

1. Should we have a content-type that is Mandatory to Implement?

Several participants spoke in favor of making the default format (currently called "application/dns-udpwireformat") mandatory, at least for servers.

2. Among the GET and POST modes of operation, which, if any, should be mandatory to implement?

Among the participants, there was consensus in favor of making both GET and POST mandatory to implement for servers.

If you would like to voice a dissenting opinion on either point, please reply on this list.  Otherwise, the chairs will regard these decisions as the group's consensus.

**Comment by paulehoffman** [comment]
See PR #128

**Comment by mcmanus** [comment]
I think most of this can be handled by the MTI PR. But I will just make a tiny clarification indicating that the server is really able to return whatever it needs to.
