### ISSUE TITLE
.well-known

### ISSUE THREAD

**Issue by mnot** [dohwg/draft-ietf-doh-dns-over-https#24]
DOH defines a well-known URI for its operation. It's not clear why this is necessary.

Well-known URIs are supposed to be for site-wide metadata; they're not intended as bootstrapping mechanisms for unrelated protocols.

Specifically, why can't DOH just define a HTTP resource time that takes requests (with query strings) in a certain format, and return responses in a certain format? I.e., use a URL to locate a DOH service, rather than a (host, port) tuple.

**Comment by bemasc** [comment]
What would you ask users to type in, to configure their client to use a particular DOH service?  (And what can we reasonably ask users to type?)

**Comment by paulehoffman** [comment]
RFC 5785 vacillates on the use of .well-known. DOH fits comfortably in the discussion in the first paragraph of section 1.1 of that document, even if it doesn't fit into the second paragraph of that section. At least a dozen of the entries in the IANA registry for .well-known seem quite similar to DOH in this regard. Wanting to change what's allowed in the registry now seems quite unwise.

**Comment by mnot** [comment]
While some registrations have been grandfathered in that doesn't follow that advice, we've been consistently applying this approach in multiple WGs for some time (e.g. CAPPORT, ROLIE, and now Eliot's MUD).

**Comment by paulehoffman** [comment]
Are you saying that we might *only* be able to do provider-supplied URLs, so there will be *no* expected interoperability? That is, instead of learning out-of-band that this web server also does DOH, I also have to learn the URL of how it does DOH? That seems onerous, and exactly the reason that .well-known has worked for others.

**Comment by martinthomson** [comment]
It means that rather than learn that `https://example.com` does DOH, you need to remember that `https://example.com/doh` is where you can do DOH.  That's substantially different from a protocol design perspective, but only marginally higher entropy for users (who have the ability to use their preferred search engine to fill in any gaps).

The idea that a name is more memorable than a URL is an odd meme.  I guess that it is technically true, but I wonder where it came from.

That path was reserved primarily for site metadata, not service discovery.  That's actually pretty clear (to me) from reading Section 1.1 of 5785, but it seems like we might need to revise that and make this point much clearer.

**Comment by mcmanus** [comment]
the .wk angle here is more about future proofing a use case DoH does not yet cover.. (and because it is explicitly not yet in scope, it is not fully defined). let's call it non-recursive push discovery. You will likely want to have more than a media type to contextualize such a push (as you could be pushing dns data without trying to push dns resolutions). A resource name with a well known meaning (a definition that has a lot in common with metadata) could do that.

the question for me is do you make that definition now (as the doh draft does) or later (when and if the functionality is defined)? The advantage of doing it now is that you get advantages around tooling etc with both models using a consistent set of uri paths by default.

**Comment by mnot** [comment]
We've had a few cases where people have asked for a .well-known "just in case" or for a potential future use, and the consistent answer (from me as expert as well as from ADs I've consulted) has been that the appropriate time to request it is when it's actually needed.

**Comment by willscott** [comment]
One of the potentially useful impacts of .well-known is the ability to auto-discover DoH capabilities as a client.

It also means that DoH prevalence could be scanned for, to track adoption rates and software compatibility of active DoH implementations.

I'm not sure I have an opinion about whether that's on the whole a good / bad thing, but it is a significant implication of this decision.

**Comment by mcmanus** [comment]
discovery and crawling for DoH requires carving out some of the global namespace - something the .well-known registry is explicitly not trying to do for services. I'm not (and never was) trying to do that.

I've been convinced that the use case I want to accommodate as a later phase does not need to be future proofed at this time via .wk in this doc. I may still ask for it to be part of .wk at that later time as I think that later use case is more consistent with site meta data than the use case being addressed by this document (which admittedly is confusing). As I said, I've been convinced that the discussion can wait for that later time. So I'll revert to the default "configure this service at whatever uri you like and then publish that out of band" model.
