### ISSUE TITLE
Describe discovery process

### ISSUE THREAD

**Issue by martinthomson** [dohwg/draft-ietf-doh-dns-over-https#3]
The draft says:

> Using the well-known path allows automated discovery of a DNS API Service,

But it probably needs to describe at least one way to perform that automated discovery.  It's probably not a good idea to have people attempt to guess.

**Comment by mcmanus** [comment]
fwiw the .wk is used here so that that when a request/response pair is pushed the client understands this to be DoH. Its probably also helpful to have a well-known path here for the normal so that defaults of https://, 443, and the default path can be used in configuration systems that might only be capable of a hostname. (e.g. my DoH server is at doh.example.com).. I'll work on text.

**Comment by mcmanus** [comment]
I think I can future proof for the context I want using a response header instead of a well known.. imo that's kind of ignoring the point of the path - but whatever. Maybe I'll propose x-well-known :)
