### ISSUE TITLE
clients MUST process dns-updwireformat?

### ISSUE THREAD

**Issue by hardaker** [dohwg/draft-ietf-doh-dns-over-https#48]
I think this may have been discussed during the DOH working group, but it conflicted with SAAG so I may have missed it if it was...

But I think it's insane to state that a client MUST support the binary DNS protocol.  The likely use cases of this protocol will be javascript or other simple (cli curl) clients making requests and I don't think these clients should be required to support a binary protocol over a transport that has traditionally helped clients adapt to their needs.  I understand requiring the server to support it, but IMHO, we should change this MUST to a SHOULD at most.

**Comment by roryhewitt** [comment]
+1

Is anyone actively working on a JSON equivalent format? I started thinking about it, but got sidetracked by my day-job.

**Comment by paulehoffman** [comment]
I have done a JSON format and decided it was The Wrong Thing To Do, but can maybe be convinced otherwise. I disagree with Wes' contention that it is "insane" if the goal is the browers/JSapp being able to send any DNS query. If you look at a JSON implementation *that is complete*, it is actually harder than parsing the DNS wireformat. Yes, it's prettier to look at, but it is in fact worse to code.

**Comment by hardaker** [comment]
No where did I say JSON.  My point was that I don't think we want to mandate that clients support real DNS parsing when there may be better formats in the future, JSON or not.

**Comment by roryhewitt** [comment]
@hardaker I mentioned JSON, because in the spec, there is mention of a mythical `application/simpledns+json` format.

@paulehoffman what made you decide that JSON is 'wrong'? I mean, if we're looking at speed, JSON ain't nice, but if we need some sort of text-based format, it's probably the only sensible way to go, unless we start using query parameters and long URL's, and that would only really work for basic queries, I think.

FWIW, all I got to was something like this:

```
{
	"format": "application/simpledns+json",
	"id": "abcd",
	"messageType": "query|response",
	"queryType": "standard|inverse|status",
	"authoritativeAnswer": true,
	"truncation": false,
	"recursionDesired": true,
	"recursionAvailable": false,
	"responseCode": "noerror|formaterror|servfail|nameerror|notimplemented|refused",
	"questionCount": 1,
	"answerCount": 0,
	"nameserverCount": 0,
	"additionalRecordsCount": 0,
	"question": {
		"label": [
			"www.example.com"
		],
		"queryType": "AA",
		"queryClass": "IN"
	}
}
```

**Comment by paulehoffman** [comment]
What I decided was "wrong" was anything that could not reproduce all the queries and responses from DNS because then we would be losing extensibility or some of the oddnesses of the DNS format. If a different format (JSON, CBOR, whatever) can do everything that wireformat can, it is inherently harder to do that plus be convertable into that format.

**Comment by martinthomson** [comment]
I think that the mistake there is not in choosing JSON, but in insisting that any alternative format be capable of representing everything that DNS does, including potential extensions.  For applications, a more limited format might be more usable.

If you accept that a limited format is useful, then a baseline of the wire format makes a lot of sense.  The wire format naturally includes all possible extensions and features of the protocol.

**Comment by mcmanus** [comment]
the bottom line question is whether we need a MTI format for max interoperability. I tend to think its a good thing and wire format is the only viable candidate that has proven itself.

**Comment by hardaker** [comment]
I think a MTI is a good thing too.  But the trick is you can't think about it as a complete bundle that binds the server and client to always both support one.  Having both sides support one is necessary for some protocols, but I don't think it is in this case.

I DO think that the server should support a mandatory protocol (and wireformat DNS seems like the only choice at the moment)

I DONT think that the client needs to mandated to support a particular encoding.  If we expect light weight clients, I'd rather have them be able to drop unneeded code from their implementation in favor of the protocol encoding they want to use.
