### ISSUE TITLE
bootstrapping / circular dependency in hostname resolution?

### ISSUE THREAD

**Issue by collinanderson** [dohwg/draft-ietf-doh-dns-over-https#52]
If DOH uses https under the hood, how does this https host name get resolved? I would have expected this to be mentioned in the RFC, though I didn't see any mention of it, besides OCSP Stapling.

Is it assumed that DOH would need to be bootstrapped by traditional DNS?

Or is it assumed that a DOH endpoint would have a TLS/SSL certificate for its ip address? (Apparently a certificate for an IP address is possible in some cases, though hard to get.)

I assume DOH is not intended to be used by home NAT routers? (How would the router get a signed TLS certificate? Maybe a DHCP response could say: use this DOH url and trust this self-signed cert for its ip address (though a certificate might be too big for a DHCP response). Or, in cases where no local DNS services are needed, the DHCP response could maybe say: use this public DOH url, here's the ip address for that hostname)

**Comment by mcmanus** [comment]
The document doesn't describe how a HTTPS client authenticates HTTPS... that's on purpose in order to simply leverage HTTPS without surprises.

as a practical matter a number of things can be done. One is TOFU as you suggest. Another is an IP based certificate which you also suggest.

Another would be to lookup the name via another, perhaps less trusted resolver, knowing that HTTPS means the IP address isn't part of the security scheme anyhow - its just a route.. subject to blocking, but not to impersonation.

Another would be to bootstrap the client with a name _and_ an address instead of one or the other.

but as a general matter I think this is one step beyond the scope of the document as its basically writing down the rules for HTTPS.

**Comment by davidkazuhiro** [comment]
This issue semi-duplicates #26

**Comment by riking** [comment]
I think this should at least be called out as an operational concern. e.g. mentioning that you probably need an alternate resolver to find the DOH server, after which you can re-query for the DOH's address as an integrity check.

**Comment by chantra** [comment]
> Another would be to bootstrap the client with a name and an address instead of one or the other.

This is the direction I have taken for [doh-stub](https://github.com/facebookexperimental/doh-proxy/blob/master/dohproxy/stub.py).
When opening a connection to the remote DOH server, if an ip was provided, it will just use that, if not, it will try to resolve using the local stub, but that may not work....

Just like an IP has always been provided to bootstrap which nameserver to use, here we need to also be provided a name so we can validate that the server we are talking to is the one we trust.
